### ISSUE TITLE
libcoinhsl is generated but libhsl works

### ISSUE THREAD

**Issue by Fabian188** [coin-or-tools/ThirdParty-HSL#16]
I built ipopt 3.14.10 without a solver (with Apple M1 I have no mkl).

Then I obtained coinhsl-2021.05.05 and was able to build it with this project following the ipopt instructions.

However libcoinhsl.dylib is built but ipopt searches for libhsl.dylib. 

Renaming helps and ipopt runs.

**Comment by amontoison** [comment]
The new `coinhsl` archive will generate `libhsl.dylib` for information.

**Comment by Fabian188** [comment]
Thanks for the feedback but I do not exactly understand. 

Do you mean I shall request again at HSL for an updated archive?

**Comment by amontoison** [comment]
No, sorry. I mean that the future `coinhsl-2022.12.XX` will generate `libhsl.dylib` instead of `libcoinhsl.dylib`.

**Comment by svigerske** [comment]
It may have been not an ideal decision that Ipopt looks for `libhsl` when loading the lib runtime, while `ThirdParty-HSL` and `coinhsl` build a `libcoinhsl`. Old versions of `ThirdParty-HSL` (up to 1.5.x) also had a flag to tell it to build a `libhsl` in addition, but that got removed when there were major updates to the buildsystem. Before that, `libcoinhsl` wasn't usable as standalone lib, so there was some more reasons to have it build a `libhsl` as well.

Changing the default in Ipopt would annoy anyone who assumes that Ipopt looks for `libhsl`, so I don't think that this will just happen. You can set the [Ipopt option hsllib](https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_hsllib) to tell it to look for `libcoinhsl.dylib`.     
Similarly, I could imagine that some would be confused if `ThirdParty-HSL` suddenly builds a `libhsl`.

**Comment by amontoison** [comment]
Is it just not possible to create a symbolic link `libhsl` at the end of the compilation in `ThirdParty-HSL` ?
If it works, we should do the same think with `coinhsl` for the Ipopt users instead of renaming the share library.

**Comment by svigerske** [comment]
It's unfortunately not **just** possible. It may be easy if libtool would support this, but as it doesn't (afaik), we would first have to find out in configure or the Makefile what the name and place of the `coinhsl` lib is for which to set a symlink (and where this symlink should put placed.)

It's easy on Linux and various other Unixes: `${DESTDIR}/${libdir}/libhsl.so` should point to `${DESTDIR}/${libdir}/libcoinhsl.so` - unless we build a static lib (but would one still want a symlink then, since that cannot be loaded by Ipopt anyway?). On macOS, the `so` would need to be `dylib`, if building a shared lib. On Windows, what ends up in `${libdir}` is the `.lib` file, which libtool names `coinhsl.dll.lib`. But the `dll`, which is of interest here, would end in `${bindir}`, and it is called `coinhsl-2.dll`.

PS: It's also possible to build both a shared and a static lib simultaneously.
